# Generated by Django 5.2.18 on 2026-10-08 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('BLING', 'Bling'), ('QUESTOR', 'Questor'), ('DOMINIO', 'Domínio'), ('FORTES', 'Fortes'), ('SCI', 'SCI'), ('ALTERDATA', 'Alterdata'), ('CONTMATIC', 'Contmatic'), ('CALIMA', 'Calima'), ('OTHER', 'Outro')], max_length=30)),
                ('status', models.CharField(choices=[('PLANNED', 'Planejada'), ('AUTHORIZATION_PENDING', 'Aguardando autorização'), ('CONNECTED', 'Conectada'), ('ERROR', 'Com erro'), ('DISABLED', 'Desativada')], default='PLANNED', max_length=30)),
                ('external_account_id', models.CharField(blank=True, max_length=180)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('non_secret_settings', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integrations', to='clients.client')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'provider'), name='uniq_provider_per_client')],
            },
        ),
    ]
