# Generated by Django 5.2.18 on 2026-10-08 23:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('COMPANY', 'Pessoa jurídica'), ('INDIVIDUAL', 'Pessoa física')], max_length=20)),
                ('tax_id', models.CharField(max_length=14)),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, max_length=255)),
                ('service_scope', models.CharField(choices=[('SERVICES', 'Prestação de serviços'), ('COMMERCE', 'Comércio'), ('MIXED', 'Mista')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('start_of_service', models.DateField()),
                ('status', models.CharField(choices=[('ONBOARDING', 'Em implantação'), ('ACTIVE', 'Ativa'), ('SUSPENDED', 'Suspensa'), ('CLOSED', 'Encerrada')], default='ONBOARDING', max_length=20)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='offices.office')),
            ],
            options={
                'ordering': ['trade_name', 'legal_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('RESPONSIBLE', 'Responsável'), ('CONTRIBUTOR', 'Colaborador'), ('VIEWER', 'Consulta')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments_granted', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_assignments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('office', 'entity_type', 'tax_id'), name='uniq_client_tax_id_per_office'),
        ),
        migrations.AddConstraint(
            model_name='clientassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('client', 'user'), name='uniq_active_client_assignment'),
        ),
    ]
